# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Game.create(gameweek: 1)
Game.create(gameweek: 2)
Game.create(gameweek: 3)
Game.create(gameweek: 4)
Game.create(gameweek: 5)
Game.create(gameweek: 6)
Game.create(gameweek: 7)
Game.create(gameweek: 8)
Game.create(gameweek: 9)
Game.create(gameweek: 10)
Game.create(gameweek: 11)
Game.create(gameweek: 12)
Game.create(gameweek: 13)
Game.create(gameweek: 14)
Game.create(gameweek: 15)
Game.create(gameweek: 16)
Game.create(gameweek: 17)
Game.create(gameweek: 18)
Game.create(gameweek: 19)
Game.create(gameweek: 20)
Game.create(gameweek: 21)
Game.create(gameweek: 22)
Game.create(gameweek: 23)
Game.create(gameweek: 24)
Game.create(gameweek: 25)
Game.create(gameweek: 26)
Game.create(gameweek: 27)
Game.create(gameweek: 28)
Game.create(gameweek: 29)
Game.create(gameweek: 30)
Game.create(gameweek: 31)
Game.create(gameweek: 32)
Game.create(gameweek: 33)
Game.create(gameweek: 34)
Game.create(gameweek: 35)
Game.create(gameweek: 36)
Game.create(gameweek: 37)
Game.create(gameweek: 38)
